### ISSUE TITLE
Bug al llamar sp getRecetasUsuario cuando una receta no tiene calificaciones

### ISSUE THREAD

**Issue by tusar-verma** [lbotano/recetasdivertidas#75]
Cuando se sube una receta nueva no tiene calificaciones. Cuando se loguea el autor de esa receta sin calificaciones salta una alerta: 
![image](https://user-images.githubusercontent.com/45916892/99979951-7236e580-2d86-11eb-8f8c-9dfc05f41207.png)

Consola:
```
Send: SERVIDORVIVE
Received: SERVIDORESTAVIVO
Send: LOGIN
Send: jorgelina
Send: jorgelina123
Received: LOGINOK
Received: false
Send: CONSTOPRECETAS
Send: 0
Received: RESPCONSULTA
Received: 1
Received: lbotano
Received: Alfajor Jorgito
Received: Es hermoso
Received: 4
Received: 2
Received: 2
Received: jorgelina
Received: Empanada
Received: Se come
Received: 1
Received: 1
Received: 3
Received: jorgelina
Received: Boquita
Received: Pasión
Received: 0
Received: 0
Send: SERVIDORVIVE
Received: SERVIDORESTAVIVO
Send: CONSCALIFUSUARIO
Send: jorgelina
Send: 1
Received: CALIFICACIONUSUARIO
Received: 3
Send: SERVIDORVIVE
Received: SERVIDORESTAVIVO
Send: CONSCALIFUSUARIO
Send: jorgelina
Send: 2
Received: CALIFICACIONUSUARIO
Received: 1
Send: SERVIDORVIVE
Received: SERVIDORESTAVIVO
Send: CONSCALIFUSUARIO
Send: jorgelina
Send: 3
Received: CALIFICACIONUSUARIO
Received: 0
Send: SERVIDORVIVE
Received: SERVIDORESTAVIVO
Send: RECETASDEUSUARIO
Send: jorgelina
Received: RESPCONSULTA
Received: 2
Received: jorgelina
Received: Empanada
Received: Se come
Received: 1
Received: 1
Received: 3
Received: jorgelina
Received: Boquita
Received: Pasión
Received: null
Received: 0
java.lang.NullPointerException
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:461)
	at io.github.recetasDivertidas.pkgRecetasDivertidas.Receta.getRecetasUsuario(Receta.java:264)
	at io.github.recetasDivertidas.pkgPerfil.Perfil.showRecetasUsuario(Perfil.java:41)
	at io.github.recetasDivertidas.pkgPerfil.Perfil.initialize(Perfil.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2673)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3323)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3280)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3249)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3222)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3199)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3192)
	at io.github.recetasDivertidas.pkgRecetasDivertidas.RecetasDivertidas.<init>(RecetasDivertidas.java:38)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346)
	at java.base/java.lang.Class.newInstance(Class.java:604)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:938)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:982)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:229)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3323)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3280)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3249)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3222)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3199)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3192)
	at io.github.recetasDivertidas.pkgLogin.Login.login(Login.java:38)
	at io.github.recetasDivertidas.pkgLogin.Login.handleKeyLogin(Login.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1729)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:4098)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2157)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2625)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at com.sun.glass.ui.View.notifyKey(View.java:971)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
El error basicamente sale porque el resultado de llamar al sp getRecetasUsuario devuelve un dato nulo, el promedio de calificación:
![image](https://user-images.githubusercontent.com/45916892/99980134-a7433800-2d86-11eb-9a20-cce79470d6bc.png)

La solución que se me ocurre es que fnGetCalificacionReceta() devuelva 0 si no tiene calificaciones

**Comment by lbotano** [comment]
Solucionado.
